version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: sre-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: sre-producer
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: sre-consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2

volumes:
  rabbitmq_data: