global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 10s